// Command import9r imports provider connections from a 9router SQLite
// database (default ~/.9router/db/data.sqlite) into onegw TOML config.
//
//	onegw-import9r -db ~/.9router/db/data.sqlite -out imported.toml
//
// Only API-key connections are imported (OAuth token flows are a v2 onegw
// feature). For openai-compatible connections the 9router nodeName/prefix
// becomes the onegw provider name (lowercased); models are discovered from
// the upstream /models endpoint when reachable. Built-in 9router providers
// without a per-connection base URL resolve from a known map, else are
// skipped with a warning. Output includes onegw gateway [auth] keys from
// 9router's apiKeys table.
package main

import (
	"database/sql"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"

	_ "modernc.org/sqlite"
)

type connRow struct {
	Provider string
	Name     string
	Priority int
	Data     string
}

type connData struct {
	APIKey               string `json:"apiKey"`
	TestStatus           string `json:"testStatus"`
	ProviderSpecificData struct {
		Prefix  string `json:"prefix"`
		APIType string `json:"apiType"`
		BaseURL string `json:"baseUrl"`
		Node    string `json:"nodeName"`
	} `json:"providerSpecificData"`
}

type account struct {
	name string
	key  string
	ok   bool // testStatus active
}

type group struct {
	name     string
	baseURL  string
	nodeName string
	accts    []account
}

// builtinBaseURL resolves 9router built-in providers that store no
// per-connection base URL. Unknown ones are skipped with a warning rather
// than emitting a config pointing at the wrong host.
var builtinBaseURL = map[string]string{
	"glm": "https://open.bigmodel.cn/api/paas/v4",
}

func main() {
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	dbPath := flag.String("db", home+"/.9router/db/data.sqlite", "path to 9router data.sqlite")
	out := flag.String("out", "", "output TOML path (default stdout)")
	flag.Parse()

	db, err := sql.Open("sqlite", *dbPath+"?_pragma=busy_timeout(3000)")
	fatal(err)
	defer db.Close()

	groups := map[string]*group{}
	rows, err := db.Query(`SELECT provider, name, priority, data FROM providerConnections
		WHERE authType = 'apikey' AND isActive = 1 ORDER BY provider, priority`)
	fatal(err)
	for rows.Next() {
		var r connRow
		fatal(rows.Scan(&r.Provider, &r.Name, &r.Priority, &r.Data))
		var d connData
		fatal(json.Unmarshal([]byte(r.Data), &d))
		psd := d.ProviderSpecificData
		base := psd.BaseURL
		node := psd.Node
		if base == "" {
			known, ok := builtinBaseURL[r.Provider]
			if !ok {
				fmt.Fprintf(os.Stderr, "skip %s (%s): no base_url known to onegw; configure manually\n", r.Provider, r.Name)
				continue
			}
			base = known
			node = r.Provider
		}
		key := strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(node, ".", "-"), " ", "-"))
		g := groups[key]
		if g == nil {
			g = &group{name: key, baseURL: base, nodeName: node}
			groups[key] = g
		}
		g.accts = append(g.accts, account{name: orDefault(r.Name, "default"), key: d.APIKey, ok: d.TestStatus == "active"})
	}
	fatal(rows.Err())
	rows.Close()

	var names []string
	for k := range groups {
		names = append(names, k)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# Generated by onegw-import9r from 9router data.sqlite\n")
	b.WriteString("# " + time.Now().UTC().Format(time.RFC3339) + "\n\n")

	// Gateway API keys: clients authenticate to onegw with these.
	var keyList []string
	krows, kerr := db.Query(`SELECT key FROM apiKeys WHERE isActive = 1`)
	if kerr == nil {
		for krows.Next() {
			var k string
			if krows.Scan(&k) == nil && k != "" {
				keyList = append(keyList, k)
			}
		}
		krows.Close()
	}
	if len(keyList) > 0 {
		b.WriteString("[auth]\nkeys = [" + quoteJoin(keyList) + "]\n\n")
	}

	b.WriteString("# --- providers ---\n\n")
	for _, name := range names {
		g := groups[name]
		kind := "openai" // openai-compatible + built-ins all speak OpenAI shape
		fmt.Fprintf(&b, "[[providers]]\nname = %q\nkind = %q\n", g.name, kind)
		if g.baseURL != "" {
			fmt.Fprintf(&b, "base_url = %q\n", strings.TrimRight(g.baseURL, "/"))
		}
		models := discoverModels(g)
		if len(models) > 0 {
			fmt.Fprintf(&b, "models = [%s]\n", quoteJoin(models))
		}
		b.WriteString("\n")
		for _, a := range g.accts {
			note := ""
			if !a.ok {
				note = " # 9router marked unavailable (429 backoff)"
			}
			fmt.Fprintf(&b, "[[providers.accounts]]\nname = %q\napi_key = %q\n%s\n", a.name, a.key, note)
		}
		b.WriteString("\n")
	}

	if *out == "" {
		os.Stdout.WriteString(b.String())
		return
	}
	fatal(os.WriteFile(*out, []byte(b.String()), 0o600))
	fmt.Fprintln(os.Stderr, "wrote", *out)
}

// discoverModels lists upstream models via GET /models using the first
// account; returns nil on any failure (pass-through routing still works via
// provider/model strings).
func discoverModels(g *group) []string {
	if g.baseURL == "" || len(g.accts) == 0 {
		return nil
	}
	client := &http.Client{Timeout: 10 * time.Second}
	req, err := http.NewRequest(http.MethodGet, strings.TrimRight(g.baseURL, "/")+"/models", nil)
	if err != nil {
		return nil
	}
	req.Header.Set("Authorization", "Bearer "+g.accts[0].key)
	resp, err := client.Do(req)
	if err != nil {
		fmt.Fprintf(os.Stderr, "note: %s models fetch failed (%v); no static model list\n", g.name, err)
		return nil
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	var parsed struct {
		Data []struct {
			ID string `json:"id"`
		} `json:"data"`
	}
	if json.Unmarshal(body, &parsed) != nil || len(parsed.Data) == 0 {
		return nil
	}
	var ids []string
	for _, m := range parsed.Data {
		if m.ID != "" {
			ids = append(ids, m.ID)
		}
	}
	return ids
}

func quoteJoin(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}

func fatal(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "import9r:", err)
		os.Exit(1)
	}
}
