#!/bin/sh
# onegw one-command installer.
#
#   curl -fsSL https://raw.githubusercontent.com/FreePeak/onegw/master/scripts/install.sh | sh
#
# What it does: downloads the latest release binary for your OS/arch, installs
# it, writes a starter config (loopback bind) with a generated admin password,
# and starts the gateway on 127.0.0.1:8080. A fresh gateway key is generated on
# each start and printed in the summary (clients send it as their API key).
#
# Env overrides:
#   ONEGW_BIN              install this local binary instead of downloading
#   ONEGW_VERSION          release tag (default: latest)
#   ONEGW_INSTALL_PREFIX   default /usr/local (falls back to ~/.local/bin)
#   ONEGW_HOME             config/log/pid dir (default ~/.onegw)
#   ONEGW_LISTEN           default 127.0.0.1:8080
#   ONEGW_KEYS             gateway client keys (default: generated)
#   ONEGW_START=0          install + config only, do not start
set -eu
REPO=FreePeak/onegw
VERSION=${ONEGW_VERSION:-latest}
PREFIX=${ONEGW_INSTALL_PREFIX:-/usr/local}
CONFHOME=${ONEGW_HOME:-$HOME/.onegw}
LISTEN=${ONEGW_LISTEN:-127.0.0.1:8080}

say() { printf '%s\n' "$*"; }
die() { printf 'install.sh: %s\n' "$*" >&2; exit 1; }

case "$(uname -s)" in
  Linux)  os=linux ;;
  Darwin) os=darwin ;;
  *) die "unsupported OS: $(uname -s)" ;;
esac
case "$(uname -m)" in
  arm64 | aarch64) arch=arm64 ;;
  x86_64 | amd64)  arch=amd64 ;;
  *) die "unsupported arch: $(uname -m)" ;;
esac

# --- fetch -------------------------------------------------------------------
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
if [ -n "${ONEGW_BIN:-}" ]; then
  cp "$ONEGW_BIN" "$tmp/onegw"
  say "using local binary $ONEGW_BIN"
else
  if [ "$VERSION" = latest ]; then
    VERSION=$(curl -fsSLI -o /dev/null -w '%{url_effective}' "https://github.com/$REPO/releases/latest" | sed 's|.*/tag/||')
    [ -n "$VERSION" ] || die "could not resolve latest release"
  fi
  say "downloading onegw $VERSION ($os/$arch)..."
  curl -fL --retry 3 -o "$tmp/onegw" "https://github.com/$REPO/releases/download/$VERSION/onegw-$os-$arch"
fi
chmod 0755 "$tmp/onegw"

# --- install -----------------------------------------------------------------
BINDIR="$PREFIX/bin"
if ! mkdir -p "$BINDIR" 2>/dev/null || [ ! -w "$BINDIR" ]; then
  BINDIR="$HOME/.local/bin"
  mkdir -p "$BINDIR"
  say "note: $PREFIX not writable, installing to $BINDIR (add it to PATH)"
fi
install -m 0755 "$tmp/onegw" "$BINDIR/onegw"

# --- starter config ----------------------------------------------------------
mkdir -p "$CONFHOME/data"
if [ ! -f "$CONFHOME/onegw.toml" ]; then
  if command -v openssl >/dev/null 2>&1; then
    ADMIN_PW=$(openssl rand -hex 12)
  else
    ADMIN_PW=$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')
  fi
  {
    echo "# generated by install.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "[server]"
    echo "listen = \"$LISTEN\""
    echo "data_dir = \"$CONFHOME/data\""
    echo "admin_password = \"$ADMIN_PW\""
    echo ""
    echo "[saver]"
    echo "enabled = true"
    echo ""
    echo "# Add [[providers]] blocks here — see:"
    echo "# https://github.com/$REPO#configuration"
  } > "$CONFHOME/onegw.toml"
  say "wrote starter config $CONFHOME/onegw.toml (admin password: $ADMIN_PW)"
fi

# --- start -------------------------------------------------------------------
if [ "${ONEGW_START:-1}" = "0" ]; then
  say "installed $BINDIR/onegw (ONEGW_START=0, not starting)"
  exit 0
fi

HOSTPORT=${LISTEN#*:}

if [ -f "$CONFHOME/onegw.pid" ] && kill -0 "$(cat "$CONFHOME/onegw.pid")" 2>/dev/null; then
  say "onegw already running (pid $(cat "$CONFHOME/onegw.pid")); restart it to pick up changes"
  say "endpoint:   http://127.0.0.1:$HOSTPORT (config: $CONFHOME/onegw.toml)"
  exit 0
fi

KEYS=${ONEGW_KEYS:-}
if [ -z "$KEYS" ]; then
  if command -v openssl >/dev/null 2>&1; then
    KEYS=$(openssl rand -hex 16)
  else
    KEYS=$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')
  fi
fi

nohup env ONEGW_CONFIG="$CONFHOME/onegw.toml" ONEGW_KEYS="$KEYS" \
  "$BINDIR/onegw" >> "$CONFHOME/onegw.log" 2>&1 &
echo $! > "$CONFHOME/onegw.pid"

# --- verify ------------------------------------------------------------------
# Probe the unauthenticated dashboard root — /admin/* is password-gated.
ok=""
i=0
while [ $i -lt 20 ]; do
  if curl -fsS -o /dev/null "http://127.0.0.1:$HOSTPORT/" 2>/dev/null; then
    ok=1
    break
  fi
  i=$((i + 1))
  sleep 1
done
[ -n "$ok" ] || die "gateway did not become healthy; check $CONFHOME/onegw.log"

say ""
say "onegw is running:"
say "  pid:         $(cat "$CONFHOME/onegw.pid")"
say "  endpoint:    http://127.0.0.1:$HOSTPORT"
say "  dashboard:   http://127.0.0.1:$HOSTPORT/  (password: $(grep '^admin_password' "$CONFHOME/onegw.toml" | cut -d'"' -f2))"
say "  gateway key: $KEYS  (clients send this as their API key)"
say "  config:      $CONFHOME/onegw.toml"
say "  log:         $CONFHOME/onegw.log"
say "  stop:        kill \$(cat $CONFHOME/onegw.pid)"
